### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sasagr** [lechium/nitoUtility#1]
While waiting for the spa, I tried to build it myself. I got this error.
Can you pls advise.
Thanks

#import "ViewController.h"
#import "Networking/SSHWrapper.h"
#import "Networking/ntvBonjourViewController.h"
#import "Networking/ObjSSH.h"
#import "SVProgressHUD/SVProgressHUD.h"
#import "UICKeyChainStore/UICKeyChainStore.h"  'UICKeyChainStore/UICKeyChainStore.h' file not found

@interface ViewController ()

@property (nonatomic, strong) ntvNetService *device;
@property (nonatomic, strong) SSHWrapper *session;
@property (nonatomic, strong) NSArray *applications;

**Comment by lechium** [comment]
all i see is contents of a header file, i dont see any build errors here....

**Comment by lechium** [comment]
nevermind i see the error now. i may have missed some files in one of my commits.

**Comment by lechium** [comment]
those files are in the repo now, it /should/ build just fine now if you pull the latest.
